### ISSUE TITLE
Metrics from some (not all) queries are missing

### ISSUE THREAD

**Issue by vintserg** [free/sql_exporter#8] opened 2018-04-24 14:05 UTC
Hi 
I use sql_exporter with Postgresql (tried last release and trunk version).
I use a collector for three queries (queries run 20-60 seconds each).

I see strange behavior - in some cases (always on the first request) the service does not return part of the rows of the sql query

Example below (the last two requests contain all the rows - see the size)
Tell me how it can be fixed?

Thank you!
``` 
root@han:~/run# wget   http://localhost:9400/metrics
--2018-04-24 16:40:06--  http://localhost:9400/metrics
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:9400... connected.
HTTP request sent, awaiting response... 200 OK
Length: 2541 (2.5K) [text/plain]
Saving to: ‘metrics.5’

metrics.5                    100%[===========================================>]   2.48K  --.-KB/s    in 0s

2018-04-24 16:40:19 (233 MB/s) - ‘metrics.5’ saved [2541/2541]

root@han:~/run# wget   http://localhost:9400/metrics
--2018-04-24 16:40:23--  http://localhost:9400/metrics
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:9400... connected.
HTTP request sent, awaiting response... 200 OK
Length: 4929 (4.8K) [text/plain]
Saving to: ‘metrics.6’

metrics.6                    100%[===========================================>]   4.81K  --.-KB/s    in 0s

2018-04-24 16:40:34 (308 MB/s) - ‘metrics.6’ saved [4929/4929]

root@han:~/run# wget   http://localhost:9400/metrics
--2018-04-24 16:40:36--  http://localhost:9400/metrics
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:9400... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6738 (6.6K) [text/plain]
Saving to: ‘metrics.7’

metrics.7                    100%[===========================================>]   6.58K  --.-KB/s    in 0s

2018-04-24 16:40:47 (51.0 MB/s) - ‘metrics.7’ saved [6738/6738]

root@han:~/run# wget   http://localhost:9400/metrics
--2018-04-24 16:40:53--  http://localhost:9400/metrics
Resolving localhost (localhost)... ::1, 127.0.0.1
Connecting to localhost (localhost)|::1|:9400... connected.
HTTP request sent, awaiting response... 200 OK
Length: 6738 (6.6K) [text/plain]
Saving to: ‘metrics.8’

metrics.8                    100%[===========================================>]   6.58K  --.-KB/s    in 0s

2018-04-24 16:41:04 (362 MB/s) - ‘metrics.8’ saved [6738/6738]

```

**Comment by free** [comment] 2018-04-24 15:34
What is the console output of your `sql_exporter` process?

I don't think some of the rows could go missing. It is more likely that one or more of your 3 queries are timing out so you're only getting the results from some of the queries, but not others. Then, on subsequent queries you get the output of all queries, either because the DB cache is warmed up and your queries run faster; or because you set a `min_interval` greater than zero in your config and you're getting cached responses.

The logging output and your config file should clarify which one it is. Or whether I'm totally missing the mark.

**Comment by vintserg** [comment] 2018-04-24 16:43
Thanks for the answer
My current config
```
global:
  scrape_timeout_offset: 500ms
  min_interval: 0s
  max_connections: 1
  max_idle_connections: 1 
``` 
Requests are performed correctly in about 60% of cases. In this case, the log is clean.

If the response is of a smaller size - the following error in the log
```
I0424 19:03:28.165545   32239 main.go:52] Starting SQL exporter (version=0.4, branch=master, revision=6dfbe982f1e42340e2a87e0d30599383c02f0bed) (go=go1.9.1, user=alin@wheat, date=20171128-15:26:05)
I0424 19:03:28.167952   32239 config.go:18] Loading configuration from /root/run/sql_exporter/day_exporter.yml
I0424 19:03:28.169399   32239 config.go:131] Loaded collector "c_day_av_prod" from /root/run/sql_exporter/av_prod.day.yml
I0424 19:03:28.170030   32239 config.go:131] Loaded collector "c_day_entries" from /root/run/sql_exporter/entries.day.yml
I0424 19:03:28.170408   32239 config.go:131] Loaded collector "c_day_prod" from /root/run/sql_exporter/prod.day.yml
I0424 19:03:28.170617   32239 main.go:67] Listening on :9400
I0424 19:04:17.048166   32239 promhttp.go:38] Error gathering metrics: 2 error(s) occurred:
* [from Gatherer #1] [, collector="c_day_prod", query="q_day_prod"] prepare query failed: context deadline exceeded
* [from Gatherer #1] [, collector="c_day_av_prod", query="q_day_av_prod"] context deadline exceeded
I0424 19:04:49.286839   32239 promhttp.go:38] Error gathering metrics: [from Gatherer #1] [, collector="c_day_prod", query="q_day_prod"] context deadline exceeded
I0424 19:05:15.140775   32239 promhttp.go:38] Error gathering metrics: [from Gatherer #1] [, collector="c_day_prod", query="q_day_prod"] context deadline exceeded

```

**Comment by free** [comment] 2018-04-29 10:56
[Apologies, was busy at work, then went on vacation and completely lost track of this email thread.]

Yup, as you can see from the logs the problem is that one of your queries (`q_day_prod`) is relatively consistently timing out. One thing you can do, looking at your config, is to increase the number of connections (and idle connections too, probably) to 3 (as it seems at least 2 of your queries are timing out sometimes). The idea behind it is that SQL Exporter is able to parallelize things down to the query level (i.e. it can run both collectors and queries belonging to the same collector in parallel as long as there are available connections). That may help, if each one of your queries is consistently able to finish by itself within whatever Prometheus' scrape timeout is AND your Postgres instance is actually able to run all 3 queries in parallel without significant slowdowns.

If all else fails, you might have to increase Prometheus' scrape timeout -- https://prometheus.io/docs/prometheus/latest/configuration/configuration/#%3Cscrape_config%3E -- to a value that will allow your queries to complete reliably.

**Comment by free** [comment] 2018-05-03 07:59
Have you had a chance to try out the configuration change(s)? If so, are you seeing an improvement?

**Comment by free** [comment] 2018-05-14 11:41
Closing, as this has to do with the database not being able to respond to all queries within Prometheus' configured scrape timeout.

Workarounds exist and have been described -- increasing the connection pool size, increasing the scrape timeout -- but this is not something that can be improved by any sort of code changes to SQL Exporter.

**Closed by free** 2018-05-14 11:41 UTC

**Comment by areinard** [comment] 2019-01-18 18:32
This issue continues to plague. This cannot be an issue with Prometheus config, as it can be recreated without prometheus running. Query averaging ~13s. 

With scrape_timeout_offset: 500ms
  min_interval: 0s
  max_connections: 6
  max_idle_connections: 6 

and simply hitting the metrics endpoint via browser recreates this issue, no prometheus involved.

**Comment by free** [comment] 2019-01-18 20:30
The [default timeout of SQL exporter is 10s](https://github.com/free/sql_exporter/blob/802289bb112f06a3dcb20e5e5f8b6f30793bf195/config/config.go#L154), that's why it times out after 10 seconds in the browser. You can override that in the configuration by setting `scrape_timeout` to something else (say "30s") [right next to `scrape_timeout_offset`](https://github.com/free/sql_exporter/blob/802289bb112f06a3dcb20e5e5f8b6f30793bf195/config/config.go#L141).

The Prometheus scrape timeout also [defaults to 10 seconds](https://prometheus.io/docs/prometheus/latest/configuration/configuration/#configuration-file) and can be overridden by setting `scrape_timeout` in the Prometheus config file (under `global` or under the specific job scrape config) to something other than `10s`. In theory, setting this latter value to something like `30s` should ensure that your query runs to completion. I'm not sure how this interacts with the scrape interval, though, i.e. what will happen if you have a `scrape_interval` of `5s` and a `scrape_timeout` of `30s`.

**Comment by edumaia01** [comment] 2022-07-06 12:52
How to insert new custom metric and query in colllector.yaml?
